name: 'Coverage'
on:
  pull_request:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - uses: artiomtr/jest-coverage-report-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          annotations: coverage
          package-manager: yarn
